### ISSUE TITLE
Gutenberg warning messages.

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/guidepost#13]
You probably already saw these but I wasn't sure if they were being generated based on our code or if they were being shown for everyone using gutenberg. 

<img width="1440" alt="screen shot 2018-09-14 at 3 30 29 pm" src="https://user-images.githubusercontent.com/158918/45573750-382b3a00-b833-11e8-9ef3-48f4281a43b4.png">

**Comment by jrtashjian** [comment]
Yes, both of these are coming from Gutenberg itself, not from Guidepost.
