### ISSUE TITLE
Sub Headings

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/guidepost#14]
I seem to be having issues with subheadings. It seems to look and work alright on the frontend but they aren't being nested on the backend. 

<img width="530" alt="screen shot 2018-09-14 at 3 34 12 pm" src="https://user-images.githubusercontent.com/158918/45573914-b5ef4580-b833-11e8-9cbd-f0e9d473b461.png">

It looks like it's being caused by this css:
.editor-block-list__block ol,
.editor-block-list__block ul {
margin: 0;
padding: 0;
}

**Comment by jrtashjian** [comment]
Looks like an update in Gutenberg caused the styling to be overridden. Patch coming in the next push.
