### ISSUE TITLE
Console error with indented links

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/guidepost#15]
When I try to click a link on an indented link nothing happens and I get this console error. This error was reported by Jason Bahl as well via email. 

<img width="1440" alt="screen shot 2018-11-15 at 6 59 48 pm" src="https://user-images.githubusercontent.com/158918/48591238-a4e0b480-e908-11e8-86af-3582455ce854.png">

You can see it live here:
https://blocks.sortabrilliant.com/test/

**Comment by jrtashjian** [comment]
Looks like the issue is the anchor text. We need to convert it into a slug format that removes the special characters. The special characters are causing the issue here.
