### ISSUE TITLE
Adding block to Core

### ISSUE THREAD

**Issue by paaljoachim** [sortabrilliant/guidepost#16]
Hey

This is an awesome block! Do please open an issue: https://github.com/WordPress/gutenberg/issues for integrating this as a new block into Gutenberg Core.

Thanks!

**Comment by nickhamze** [comment]
Thanks for checking Guidepost out. 

I'm not sure on the process of recommending blocks to be added to core but I'll look into it.

**Comment by paaljoachim** [comment]
Hey Nick

You could say something like this in a new issue (or existing issue)...
I have built this block plugin and does so and so (+ add screenshots). It would be great if Core could add a block that does something similar. Feel free to use my code.
