### ISSUE TITLE
General Maintenance 

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/guidepost#23]
The plugins seems to work ok (double check if you can) but it needs a little maintenance.

- Removing legacy Github updater code
- Updating package.json to remove vulnerable dependencies
- Add blocks.json following the instructions here (https://github.com/WordPress/wporg-plugin-guidelines/blob/block-guidelines/blocks.md#4-block-plugins-must-include-a-blockjson-file)

**Comment by jrtashjian** [comment]
Done. Here's the `block.json` file: https://github.com/sortabrilliant/guidepost/blob/master/src/block.json
