### ISSUE TITLE
Core block?

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/guidepost#24]
I wish I would have saw this yesterday, probably not worth updating this plugin anymore. 

What do you think?

It looks like the idea is being merged into core sometime in the future:
https://github.com/WordPress/gutenberg/pull/15426

**Comment by nickhamze** [comment]
Maybe I'll brainstorm some ways to differentiate our block from the core offerings. This was our first block and I'm a bit sentimental about it. Let's keep it alive.

**Comment by jrtashjian** [comment]
I'm a little sentimental about it too :)

Looks like that PR in core is super stale and is based on our block anyway. I say we update it (it's broken right now) and it's performance can be improved in doing so.

**Comment by nickhamze** [comment]
Sounds good. You get it working again and I'll think of some cool new features that no one else has.
