### ISSUE TITLE
Multiple identical headings generates same anchor ID

### ISSUE THREAD

**Issue by LukaszJaro** [sortabrilliant/guidepost#25]
This prevents jumping to the next anchor since the ID's are the same, it will always just land on first available anchor heading.

Possible solution to add serial ids like WordPress permalinks when there is a duplicate? 

Anchor: #example, #example-2

Duplicate headings: Example, Example

**Comment by jrtashjian** [comment]
This has been fixed in v1.2.0 (just deployed).
