### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by chriscoyier** [sortabrilliant/guidepost#30]
Not sure any of these are bugs, so feel free to close, but just noting some things that feel weird to me.

### Visual

These are nested headers:

<img width="626" alt="Screen Shot 2020-03-16 at 7 21 05 AM" src="https://user-images.githubusercontent.com/69156/76767386-c220cf80-6756-11ea-85be-927169681d3c.png">

I see they output as nested lists, but it seems strange they aren't nested lists here. 

I also wonder if the block could/should have some kind of visual distinction about what it is. This looks like a normal text block, so looks and feels like it should be editable, but obviously it isn't. 

### Output

Each `<li>` has a `<div class="components-disabled">` within it, which seems weird to me and for my particular CSS, breaks the bullet post styling. That div is in the database too right? Is that what is required in the block to prevent editing on the admin side? 

<img width="489" alt="Screen Shot 2020-03-16 at 7 23 22 AM" src="https://user-images.githubusercontent.com/69156/76767700-41160800-6757-11ea-9173-d46086662d2b.png">

### DB

This is probably a generic Gutenberg question in general, but what happens if someday I disable this plugin? Does the block's HTML still stay there, but now manually editable?

**Comment by nickhamze** [comment]
Hey @chriscoyier,

Thanks for your feedback. 

**Nesting:** We don't add much CSS ourselves and instead have it inherit the styles of the theme but we probably should add a fallback for themes that don't provide nested list styles. 

**Visual Distinction:** This is a great point. Do you have any ideas about how this would look? I think it's something that is needed and we can easily implement this.

**Output & DB:** I'm not a developer but I don't remember it doing this before. I don't see this code present in our plugin code so it must be added by the block editor. For this question and the one about the DB I'll have to defer to @jrtashjian who actually knows how all this works :) .

**Comment by jrtashjian** [comment]
@chriscoyier good catch on that `components-disabled` div, it shouldn't be there and I'll get it removed this week.

The block's HTML is saved into the post_content so even if you were to disable the plugin in the future, the content will still exist and work. If you edit a post that had this block added and the plugin is disabled, it will display a warning but will allow you to convert it to another block (like a list block for example). Whether or not you convert it the HTML will still work.

**Comment by jrtashjian** [comment]
- Extraneous divs removed in: https://github.com/sortabrilliant/guidepost/commit/76708669cc127bf58d651862d1ca9193b4e2e84f
- Default spacing fixed in: https://github.com/sortabrilliant/guidepost/commit/a1dbb4c3f45a361f3b62df43a9344c6f71c543ae

**Comment by chriscoyier** [comment]
Thanks team! I hope the plugin is a smidge better for it.
